# Generated by Django 5.1.3 on 2024-11-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgLangs',
            fields=[
                ('Language', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=255)),
                ('SchoolAddress', models.CharField(max_length=255)),
                ('PrincipalName', models.CharField(max_length=255)),
                ('PrincipalEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Term', models.CharField(max_length=20)),
                ('ExtraMember', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.IntegerField(choices=[(0, 'CSAPAT'), (1, 'SZERVEZŐ'), (2, 'ISKOLA')], default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=30)),
                ('Mentor', models.CharField(max_length=30)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dusza_app.school')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dusza_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dusza_app.user'),
        ),
    ]
