# Generated by Django 5.1.3 on 2024-11-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusza_app', '0002_teammember_team_alter_school_id_alter_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dusza_app.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dusza_app.team'),
        ),
    ]
