# Generated by Django 5.1.3 on 2024-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusza_app', '0003_remove_school_user_remove_team_user_user_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Team'), (1, 'Organizer'), (2, 'School')], default=0),
        ),
    ]
