# Generated by Django 5.1.3 on 2024-11-09 22:48

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusza_app', '0008_alter_user_school_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator('^[\\w @+.-]+$', 'Egy érvényes felhasználónév csak betűkből, számokból, szóközökből és az alábbi speciális karakterkből állhat: [^,$,@,&] (maximum karakterszám: 150)')]),
        ),
    ]
