# Generated by Django 5.1.3 on 2024-11-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusza_app', '0009_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principalEmail',
            new_name='principal_email',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='principalName',
            new_name='principal_name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='schoolAddress',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='schoolName',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamName',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='extraMember',
            new_name='extra_member',
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dusza_app.category'),
        ),
        migrations.AddField(
            model_name='team',
            name='programming_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dusza_app.proglangs'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.IntegerField(choices=[(0, 'Regisztrált'), (1, 'Tanárok által jóváhagyva'), (2, 'Szervezők által jóváhagyva')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Team'), (1, 'Organizer'), (2, 'School'), (3, 'Admin')], default=0),
        ),
    ]
